# SC2View Configuration

# Window settings
[window]
title = "AiurGaze"
width = 1920.0
height = 1080.0
resizable = true

# StarCraft II settings
[starcraft]
upstream_url = "ws://127.0.0.1"
upstream_port = 5555
listen_url = "127.0.0.1"
listen_port = 5000
image = "sc2:latest"
container_name = "sc2-tweak"

# Game config panel defaults
[game_config_panel]
game_type = "VsAI"           # "VsAI" or "VsBot"
map_name = "AbyssalReefAIE.SC2Map"
player_name = "Player1"
ai_difficulty = "Medium"
ai_race = "Random"
bot_name = "BotOpponent"
disable_fog = true
random_seed = 42
realtime = false