# Window settings
[window]
width = 1920.0
height = 1080.0
resizable = true

# StarCraft II settings
[starcraft]
upstream_url = "ws://127.0.0.1"
upstream_port = 5555
listen_url = "127.0.0.1"
listen_port = 5000
image = "minimal-sc2:latest"
container_name = "aiurgaze-sc2"

# Game config panel defaults
[game_config_panel]
game_type = "VsAI"           # "VsAI" or "VsBot"
map_name = "AbyssalReefAIE.SC2Map"
player_name = "Player1"
ai_difficulty = "Medium"
ai_race = "Random"
bot_name = "BotOpponent"
disable_fog = true
random_seed = 42
realtime = false
bot_command = ""             # Bash command to run player bot (if set)
bot_opponent_command = ""    # Bash command to run opponent bot (if set, only for VsBot mode)
