tile_size = 16.0

[[entity]]
id = 4
name = "Colossus"
icon = "icons/Colossus.webp"

[[entity]]
id = 5
name = "TechLab"
icon = "icons/TechLab.webp"

[[entity]]
id = 6
name = "Reactor"
icon = "icons/Reactor.webp"

[[entity]]
id = 7
name = "InfestorTerran"
icon = "icons/InfestedTerran.webp"

[[entity]]
id = 8
name = "BanelingCocoon"
icon = "icons/Baneling.webp"

[[entity]]
id = 9
name = "Baneling"
icon = "icons/Baneling.webp"

[[entity]]
id = 10
name = "Mothership"
icon = "icons/Mothership.webp"

[[entity]]
id = 11
name = "PointDefenseDrone"
icon = "icons/PointDefenseDrone.webp"

[[entity]]
id = 12
name = "Changeling"
icon = "icons/Changeling.webp"

[[entity]]
id = 13
name = "ChangelingZealot"
icon = "icons/ChangelingZealot.webp"

[[entity]]
id = 14
name = "ChangelingMarineShield"
icon = "icons/ChangelingMarineShield.webp"

[[entity]]
id = 15
name = "ChangelingMarine"
icon = "icons/ChangelingMarine.webp"

[[entity]]
id = 16
name = "ChangelingZerglingWings"
icon = "icons/ChangelingZerglingWings.webp"

[[entity]]
id = 17
name = "ChangelingZergling"
icon = "icons/ChangelingZergling.webp"

[[entity]]
id = 18
name = "CommandCenter"
icon = "icons/CommandCenter.webp"

[[entity]]
id = 19
name = "SupplyDepot"
icon = "icons/SupplyDepot.webp"

[[entity]]
id = 20
name = "Refinery"
icon = "icons/Refinery.webp"

[[entity]]
id = 21
name = "Barracks"
icon = "icons/Barracks.webp"

[[entity]]
id = 22
name = "EngineeringBay"
icon = "icons/EngineeringBay.webp"

[[entity]]
id = 23
name = "MissileTurret"
icon = "icons/MissileTurret.webp"

[[entity]]
id = 24
name = "Bunker"
icon = "icons/Bunker.webp"

[[entity]]
id = 25
name = "SensorTower"
icon = "icons/SensorTower.webp"

[[entity]]
id = 26
name = "GhostAcademy"
icon = "icons/GhostAcademy.webp"

[[entity]]
id = 27
name = "Factory"
icon = "icons/Factory.webp"

[[entity]]
id = 28
name = "Starport"
icon = "icons/Starport.webp"

[[entity]]
id = 29
name = "Armory"
icon = "icons/Armory.webp"

[[entity]]
id = 30
name = "FusionCore"
icon = "icons/FusionCore.webp"

[[entity]]
id = 31
name = "AutoTurret"
icon = "icons/AutoTurret.webp"

[[entity]]
id = 32
name = "SiegeTankSieged"
icon = "icons/SiegeTankSieged.webp"

[[entity]]
id = 33
name = "SiegeTank"
icon = "icons/SiegeTank.webp"

[[entity]]
id = 34
name = "VikingAssault"
icon = "icons/VikingAssault.webp"

[[entity]]
id = 35
name = "VikingFighter"
icon = "icons/VikingFighter.webp"

[[entity]]
id = 36
name = "CommandCenterFlying"
icon = "icons/CommandCenterFlying.webp"

[[entity]]
id = 37
name = "BarracksTechLab"
icon = "icons/BarracksTechLab.webp"

[[entity]]
id = 38
name = "BarracksReactor"
icon = "icons/BarracksReactor.webp"

[[entity]]
id = 39
name = "FactoryTechLab"
icon = "icons/FactoryTechLab.webp"

[[entity]]
id = 40
name = "FactoryReactor"
icon = "icons/FactoryReactor.webp"

[[entity]]
id = 41
name = "StarportTechLab"
icon = "icons/StarportTechLab.webp"

[[entity]]
id = 42
name = "StarportReactor"
icon = "icons/StarportReactor.webp"

[[entity]]
id = 43
name = "FactoryFlying"
icon = "icons/FactoryFlying.webp"

[[entity]]
id = 44
name = "StarportFlying"
icon = "icons/StarportFlying.webp"

[[entity]]
id = 45
name = "SCV"
icon = "icons/SCV.webp"

[[entity]]
id = 46
name = "BarracksFlying"
icon = "icons/BarracksFlying.webp"

[[entity]]
id = 47
name = "SupplyDepotLowered"
icon = "icons/SupplyDepotLowered.webp"

[[entity]]
id = 48
name = "Marine"
icon = "icons/Marine.webp"

[[entity]]
id = 49
name = "Reaper"
icon = "icons/Reaper.webp"

[[entity]]
id = 50
name = "Ghost"
icon = "icons/Ghost.webp"

[[entity]]
id = 51
name = "Marauder"
icon = "icons/Marauder.webp"

[[entity]]
id = 52
name = "Thor"
icon = "icons/Thor.webp"

[[entity]]
id = 53
name = "Hellion"
icon = "icons/Hellion.webp"

[[entity]]
id = 54
name = "Medivac"
icon = "icons/Medivac.webp"

[[entity]]
id = 55
name = "Banshee"
icon = "icons/Banshee.webp"

[[entity]]
id = 56
name = "Raven"
icon = "icons/Raven.webp"

[[entity]]
id = 57
name = "Battlecruiser"
icon = "icons/Battlecruiser.webp"

[[entity]]
id = 58
name = "Nuke"
icon = "icons/Nuke.webp"

[[entity]]
id = 59
name = "Nexus"
icon = "icons/Nexus.webp"

[[entity]]
id = 60
name = "Pylon"
icon = "icons/Pylon.webp"

[[entity]]
id = 61
name = "Assimilator"
icon = "icons/Assimilator.webp"

[[entity]]
id = 62
name = "Gateway"
icon = "icons/Gateway.webp"

[[entity]]
id = 63
name = "Forge"
icon = "icons/Forge.webp"

[[entity]]
id = 64
name = "FleetBeacon"
icon = "icons/FleetBeacon.webp"

[[entity]]
id = 65
name = "TwilightCouncil"
icon = "icons/TwilightCouncil.webp"

[[entity]]
id = 66
name = "PhotonCannon"
icon = "icons/PhotonCannon.webp"

[[entity]]
id = 67
name = "Stargate"
icon = "icons/Stargate.webp"

[[entity]]
id = 68
name = "TemplarArchive"
icon = "icons/TemplarArchive.webp"

[[entity]]
id = 69
name = "DarkShrine"
icon = "icons/DarkShrine.webp"

[[entity]]
id = 70
name = "RoboticsBay"
icon = "icons/RoboticsBay.webp"

[[entity]]
id = 71
name = "RoboticsFacility"
icon = "icons/RoboticsFacility.webp"

[[entity]]
id = 72
name = "CyberneticsCore"
icon = "icons/CyberneticsCore.webp"

[[entity]]
id = 73
name = "Zealot"
icon = "icons/Zealot.webp"

[[entity]]
id = 74
name = "Stalker"
icon = "icons/Stalker.webp"

[[entity]]
id = 75
name = "HighTemplar"
icon = "icons/HighTemplar.webp"

[[entity]]
id = 76
name = "DarkTemplar"
icon = "icons/DarkTemplar.webp"

[[entity]]
id = 77
name = "Sentry"
icon = "icons/Sentry.webp"

[[entity]]
id = 78
name = "Phoenix"
icon = "icons/Phoenix.webp"

[[entity]]
id = 79
name = "Carrier"
icon = "icons/Carrier.webp"

[[entity]]
id = 80
name = "VoidRay"
icon = "icons/VoidRay.webp"

[[entity]]
id = 81
name = "WarpPrism"
icon = "icons/WarpPrism.webp"

[[entity]]
id = 82
name = "Observer"
icon = "icons/Observer.webp"

[[entity]]
id = 83
name = "Immortal"
icon = "icons/Immortal.webp"

[[entity]]
id = 84
name = "Probe"
icon = "icons/Probe.webp"

[[entity]]
id = 85
name = "Interceptor"
icon = "icons/Interceptor.webp"

[[entity]]
id = 86
name = "Hatchery"
icon = "icons/Hatchery.webp"

[[entity]]
id = 87
name = "CreepTumor"
icon = "icons/CreepTumor.webp"

[[entity]]
id = 88
name = "Extractor"
icon = "icons/Extractor.webp"

[[entity]]
id = 89
name = "SpawningPool"
icon = "icons/SpawningPool.webp"

[[entity]]
id = 90
name = "EvolutionChamber"
icon = "icons/EvolutionChamber.webp"

[[entity]]
id = 91
name = "HydraliskDen"
icon = "icons/HydraliskDen.webp"

[[entity]]
id = 92
name = "Spire"
icon = "icons/Spire.webp"

[[entity]]
id = 93
name = "UltraliskCavern"
icon = "icons/UltraliskCavern.webp"

[[entity]]
id = 94
name = "InfestationPit"
icon = "icons/InfestationPit.webp"

[[entity]]
id = 95
name = "NydusNetwork"
icon = "icons/NydusNetwork.webp"

[[entity]]
id = 96
name = "BanelingNest"
icon = "icons/BanelingNest.webp"

[[entity]]
id = 97
name = "RoachWarren"
icon = "icons/RoachWarren.webp"

[[entity]]
id = 98
name = "SpineCrawler"
icon = "icons/SpineCrawler.webp"

[[entity]]
id = 99
name = "SporeCrawler"
icon = "icons/SporeCrawler.webp"

[[entity]]
id = 100
name = "Lair"
icon = "icons/Lair.webp"

[[entity]]
id = 101
name = "Hive"
icon = "icons/Hive.webp"

[[entity]]
id = 102
name = "GreaterSpire"
icon = "icons/GreaterSpire.webp"

[[entity]]
id = 103
name = "Egg"
icon = "icons/Egg.webp"

[[entity]]
id = 104
name = "Drone"
icon = "icons/Drone.webp"

[[entity]]
id = 105
name = "Zergling"
icon = "icons/Zergling.webp"

[[entity]]
id = 106
name = "Overlord"
icon = "icons/Overlord.webp"

[[entity]]
id = 107
name = "Hydralisk"
icon = "icons/Hydralisk.webp"

[[entity]]
id = 108
name = "Mutalisk"
icon = "icons/Mutalisk.webp"

[[entity]]
id = 109
name = "Ultralisk"
icon = "icons/Ultralisk.webp"

[[entity]]
id = 110
name = "Roach"
icon = "icons/Roach.webp"

[[entity]]
id = 111
name = "Infestor"
icon = "icons/Infestor.webp"

[[entity]]
id = 112
name = "Corruptor"
icon = "icons/Corruptor.webp"

[[entity]]
id = 113
name = "BroodLordCocoon"
icon = "icons/BroodLord.webp"

[[entity]]
id = 114
name = "BroodLord"
icon = "icons/BroodLord.webp"

[[entity]]
id = 115
name = "BanelingBurrowed"
icon = "icons/BanelingBurrowed.webp"

[[entity]]
id = 116
name = "DroneBurrowed"
icon = "icons/DroneBurrowed.webp"

[[entity]]
id = 117
name = "HydraliskBurrowed"
icon = "icons/HydraliskBurrowed.webp"

[[entity]]
id = 118
name = "RoachBurrowed"
icon = "icons/RoachBurrowed.webp"

[[entity]]
id = 119
name = "ZerglingBurrowed"
icon = "icons/ZerglingBurrowed.webp"

[[entity]]
id = 120
name = "InfestorTerranBurrowed"
icon = "icons/InfestorTerranBurrowed.webp"

[[entity]]
id = 125
name = "QueenBurrowed"
icon = "icons/QueenBurrowed.webp"

[[entity]]
id = 126
name = "Queen"
icon = "icons/Queen.webp"

[[entity]]
id = 127
name = "InfestorBurrowed"
icon = "icons/InfestorBurrowed.webp"

[[entity]]
id = 128
name = "OverlordCocoon"
icon = "icons/Overlord.webp"

[[entity]]
id = 129
name = "Overseer"
icon = "icons/Overseer.webp"

[[entity]]
id = 130
name = "PlanetaryFortress"
icon = "icons/PlanetaryFortress.webp"

[[entity]]
id = 131
name = "UltraliskBurrowed"
icon = "icons/UltraliskBurrowed.webp"

[[entity]]
id = 132
name = "OrbitalCommand"
icon = "icons/OrbitalCommand.webp"

[[entity]]
id = 133
name = "WarpGate"
icon = "icons/WarpGate.webp"

[[entity]]
id = 134
name = "OrbitalCommandFlying"
icon = "icons/OrbitalCommandFlying.webp"

[[entity]]
id = 136
name = "WarpPrismPhasing"
icon = "icons/WarpPrismPhasing.webp"

[[entity]]
id = 137
name = "CreepTumorBurrowed"
icon = "icons/CreepTumorBurrowed.webp"

[[entity]]
id = 138
name = "CreepTumorQueen"
icon = "icons/CreepTumorQueen.webp"

[[entity]]
id = 139
name = "SpineCrawlerUprooted"
icon = "icons/SpineCrawlerUprooted.webp"

[[entity]]
id = 140
name = "SporeCrawlerUprooted"
icon = "icons/SporeCrawlerUprooted.webp"

[[entity]]
id = 141
name = "Archon"
icon = "icons/Archon.webp"

[[entity]]
id = 142
name = "NydusCanal"
icon = "icons/NydusCanal.webp"

[[entity]]
id = 145
name = "GhostNova"
icon = "icons/GhostNova.webp"

[[entity]]
id = 150
name = "InfestedTerransEgg"
icon = "icons/InfestedTerransEgg.webp"

[[entity]]
id = 151
name = "Larva"
icon = "icons/Larva.webp"

[[entity]]
id = 268
name = "MULE"
icon = "icons/MULE.webp"

[[entity]]
id = 289
name = "Broodling"
icon = "icons/Broodling.webp"

[[entity]]
id = 311
name = "Adept"
icon = "icons/Adept.webp"

[[entity]]
id = 339
name = "InfestedTerransEggPlacement"
icon = "icons/InfestedTerransEggPlacement.webp"

[[entity]]
id = 484
name = "HellionTank"
icon = "icons/Hellbat.webp"

[[entity]]
id = 488
name = "MothershipCore"
icon = "icons/MothershipCore.webp"

[[entity]]
id = 489
name = "LocustMP"
icon = "icons/LocustMP.webp"

[[entity]]
id = 491
name = "NydusCanalAttacker"
icon = "icons/NydusCanalAttacker.webp"

[[entity]]
id = 492
name = "NydusCanalCreeper"
icon = "icons/NydusCanalCreeper.webp"

[[entity]]
id = 493
name = "SwarmHostBurrowedMP"
icon = "icons/SwarmHostBurrowedMP.webp"

[[entity]]
id = 494
name = "SwarmHostMP"
icon = "icons/SwarmHostMP.webp"

[[entity]]
id = 495
name = "Oracle"
icon = "icons/Oracle.webp"

[[entity]]
id = 496
name = "Tempest"
icon = "icons/Tempest.webp"

[[entity]]
id = 497
name = "WarHound"
icon = "icons/WarHound.webp"

[[entity]]
id = 498
name = "WidowMine"
icon = "icons/WidowMine.webp"

[[entity]]
id = 499
name = "Viper"
icon = "icons/Viper.webp"

[[entity]]
id = 500
name = "WidowMineBurrowed"
icon = "icons/WidowMineBurrowed.webp"

[[entity]]
id = 501
name = "LurkerMPEgg"
icon = "icons/LurkerMPEgg.webp"

[[entity]]
id = 502
name = "LurkerMP"
icon = "icons/LurkerMP.webp"

[[entity]]
id = 503
name = "LurkerMPBurrowed"
icon = "icons/LurkerMPBurrowed.webp"

[[entity]]
id = 504
name = "LurkerDenMP"
icon = "icons/LurkerDenMP.webp"

[[entity]]
id = 569
name = "ResourceBlocker"
icon = "icons/ResourceBlocker.webp"

[[entity]]
id = 593
name = "IceProtossCrates"
icon = "icons/IceProtossCrates.webp"

[[entity]]
id = 594
name = "ProtossCrates"
icon = "icons/ProtossCrates.webp"

[[entity]]
id = 595
name = "TowerMine"
icon = "icons/TowerMine.webp"

[[entity]]
id = 687
name = "RavagerCocoon"
icon = "icons/RavagerCocoon.webp"

[[entity]]
id = 688
name = "Ravager"
icon = "icons/Ravager.webp"

[[entity]]
id = 689
name = "Liberator"
icon = "icons/Liberator.webp"

[[entity]]
id = 690
name = "RavagerBurrowed"
icon = "icons/RavagerBurrowed.webp"

[[entity]]
id = 691
name = "ThorAP"
icon = "icons/ThorAP.webp"

[[entity]]
id = 692
name = "Cyclone"
icon = "icons/Cyclone.webp"

[[entity]]
id = 693
name = "LocustMPFlying"
icon = "icons/LocustMPFlying.webp"

[[entity]]
id = 694
name = "Disruptor"
icon = "icons/Disruptor.webp"

[[entity]]
id = 725
name = "VoidMPImmortalReviveCorpse"
icon = "icons/VoidMPImmortalReviveCorpse.webp"

[[entity]]
id = 726
name = "GuardianCocoonMP"
icon = "icons/GuardianCocoonMP.webp"

[[entity]]
id = 727
name = "GuardianMP"
icon = "icons/GuardianMP.webp"

[[entity]]
id = 728
name = "DevourerCocoonMP"
icon = "icons/DevourerCocoonMP.webp"

[[entity]]
id = 729
name = "DevourerMP"
icon = "icons/DevourerMP.webp"

[[entity]]
id = 730
name = "DefilerMPBurrowed"
icon = "icons/DefilerMPBurrowed.webp"

[[entity]]
id = 731
name = "DefilerMP"
icon = "icons/DefilerMP.webp"

[[entity]]
id = 732
name = "OracleStasisTrap"
radius = 0.4375
icon = "icons/StasisWard.webp"

[[entity]]
id = 733
name = "DisruptorPhased"
icon = "icons/DisruptorPhased.webp"

[[entity]]
id = 734
name = "LiberatorAG"
radius = 0.75
icon = "icons/LiberatorAG.webp"

[[entity]]
id = 800
name = "ReleaseInterceptorsBeacon"
radius = 1.5
icon = "icons/ReleaseInterceptorsBeacon.webp"

[[entity]]
id = 801
name = "AdeptPhaseShift"
icon = "icons/AdeptPhaseShift.webp"

[[entity]]
id = 820
name = "HERCPlacement"
radius = 0.6875
icon = "icons/HERCPlacement.webp"

[[entity]]
id = 838
name = "HERC"
icon = "icons/HERC.webp"

[[entity]]
id = 840
name = "Replicant"
icon = "icons/Replicant.webp"

[[entity]]
id = 855
name = "CorsairMP"
icon = "icons/CorsairMP.webp"

[[entity]]
id = 856
name = "ScoutMP"
icon = "icons/ScoutMP.webp"

[[entity]]
id = 857
name = "ArbiterMP"
icon = "icons/ArbiterMP.webp"

[[entity]]
id = 858
name = "ScourgeMP"
icon = "icons/ScourgeMP.webp"

[[entity]]
id = 860
name = "QueenMP"
icon = "icons/QueenMP.webp"

[[entity]]
id = 891
name = "Elsecaro_Colonist_Hut"
icon = "icons/Elsecaro_Colonist_Hut.webp"

[[entity]]
id = 892
name = "TransportOverlordCocoon"
icon = "icons/Overlord.webp"

[[entity]]
id = 893
name = "OverlordTransport"
icon = "icons/OverlordTransport.webp"

[[entity]]
id = 894
name = "PylonOvercharged"
icon = "icons/Pylon.webp"

[[entity]]
id = 895
name = "BypassArmorDrone"
icon = "icons/BypassArmorDrone.webp"

[[entity]]
id = 1910
name = "ShieldBattery"
icon = "icons/ShieldBattery.webp"

[[entity]]
id = 1911
name = "ObserverSiegeMode"
icon = "icons/Observer.webp"

[[entity]]
id = 1912
name = "OverseerSiegeMode"
icon = "icons/Overseer.webp"

[[entity]]
id = 1913
name = "RavenRepairDrone"
icon = "icons/RavenRepairDrone.webp"

[[entity]]
id = 1940
name = "Viking"
icon = "icons/Viking.webp"

[[entity]]
id = 1943
name = "RefineryRich"
radius = 1.6875
icon = "icons/RefineryRich.webp"

[[entity]]
id = 1994
name = "AssimilatorRich"
icon = "icons/AssimilatorRich.webp"

[[entity]]
id = 1995
name = "ExtractorRich"
icon = "icons/ExtractorRich.webp"

[[entity]]
id = 342
name = "VespeneGeyser"
icon = "icons/VespeneGeyser.webp"

[[entity]]
id = 344
name = "RichVespeneGeyser"
icon = "icons/VespeneGeyser.webp"
